In [86]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd
import torch
import torchvision
from torchvision import datasets, transforms
from torch import nn, optim, flatten
from torch.nn import Linear, Conv2d, MaxPool2d, BatchNorm2d, Module, Dropout, ReLU
import torch.nn.functional as F
torch.manual_seed(0)
from sklearn.decomposition import PCA 
from numpy.linalg import eig
#from autograd_lib import autograd_lib
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cpu')

In [6]:
x = torch.linspace(0.01,1,300)
x=x[:,None]
y = np.sin(5 * 3.142 * x)/(5 * 3.142 * x)

In [7]:
class Network(nn.Module):
    def __init__(self):
        super(Network, self).__init__()
        self.fc1 = nn.Linear(1,30)
        self.fc2 = nn.Linear(30,70)
        self.fc3 = nn.Linear(70,1)
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)        
        return x

In [107]:
#Calculate Gradient Norm
def grad_norm():
    grad_all = 0.0
    for p in model.parameters():
        grad =0
        if p.grad is not None:
            grad = (p.grad.cpu().data.numpy() ** 2).sum()
        grad_all+=grad
    grad_norm = grad_all**0.5
    return grad_norm

grad_list = grad_norm()
grad_list

0.24587066145027914

In [102]:
def lossfn(x):
    loss = loss_fn(output, y)
    return loss

In [135]:
def gradloss(b):
    loss = loss_fn(torch.tensor(grad_norm()), b)
    #print(type(loss))
    return loss
l = gradloss(torch.tensor(0.0))
type(l)

torch.Tensor

In [132]:
def retloss(loss):
    return loss

In [141]:
epochs =1000
model = Network()
loss_fn = torch.nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
errorloss =[]
costVector = []
for i in range(10):
    for xi,yi in zip(x,y):
        optimizer.zero_grad()
        output = model(xi)
        loss = loss_fn(output, yi)
        #print(loss.item())
        loss.backward()
        loss_norm = gradloss(torch.tensor(0.0))
        #loss_norm = loss_fn(torch.tensor(grad_norm()),torch.tensor(0.0))
        optimizer.step()
        #print(type(loss_norm))
        #print(loss_norm.item())

        h = torch.autograd.functional.hessian(retloss, loss)
        #h_eig = torch.symeig(h).eigenvalues 
h

tensor(0.)

In [ ]:
inputs = torch.rand(2, 2)
h = torch.autograd.functional.hessian(lossfn, inputs)
e_value, e_vector = eig(h)
e_vector[0][0]
h

In [ ]:
for i in range(9):
    optimizer.zero_grad()
    output = model(x)
    loss = loss_fn(model)
    errorloss.append(loss.item())
    print(loss)
    
    h = torch.autograd.functional.hessian(lossfn, x, create_graph=True)
w,v = eig(h)

In [129]:
print(x[:4])

tensor([[0.0100],
        [0.0133],
        [0.0166],
        [0.0199]])


In [130]:
for xi,yi in zip(x[:4],y[:4]):
    print(xi,yi)

tensor([0.0100]) tensor([0.9959])
tensor([0.0133]) tensor([0.9927])
tensor([0.0166]) tensor([0.9887])
tensor([0.0199]) tensor([0.9837])
